import { NextResponse } from "next/server";
import { withRoute } from "@/lib/api-route";
import { projectRouteSchema } from "@/lib/clawops-schemas";
import { getJobExecutions, getProject, listJobs, listProjectDocuments } from "@/lib/clawops-store";
import { runLocalCliCapture } from "@/lib/openclaw";
import { gatewayCall } from "@/lib/openclaw";
function repoName(url:string){try{const u=new URL(url);const m=u.pathname.replace(/^\/|\.git$/g,"").split("/");return m.length>=2?`${m[0]}/${m[1]}`:null;}catch{return null;}}
async function github(repository:string){const name=repoName(repository);if(!name)return {repository,available:false,error:"Unsupported repository URL"};try{const r=await runLocalCliCapture(["gh","repo","view",name,"--json","nameWithOwner,url,description,defaultBranchRef,isFork,parent,updatedAt"],15_000);if(r.code!==0)throw new Error(r.stderr||"gh failed");return {repository,available:true,...JSON.parse(r.stdout)};}catch(e){return {repository,available:false,error:e instanceof Error?e.message:String(e)};}}
async function discord(){try{const s=await gatewayCall<Record<string,unknown>>("channels.status",{},8_000);const channels=(s.channels&&typeof s.channels==="object"?s.channels:{}) as Record<string,Record<string,unknown>>;const row=channels.discord;return {configured:Boolean(row),connected:row?.running===true||((row?.probe as Record<string,unknown>|undefined)?.ok===true),mode:"openclaw-channel",notifications:"disabled-until-explicit-destination"};}catch(e){return {configured:false,connected:false,mode:"openclaw-channel",notifications:"unavailable",error:e instanceof Error?e.message:String(e)};}}
export const GET=withRoute({name:"/api/projects/[slug]/overview",routeSchema:projectRouteSchema},async(_r,ctx)=>{const project=await getProject(ctx.params.slug),jobs=await listJobs({project:project.slug});const executions=(await Promise.all(jobs.map(async j=>(await getJobExecutions(j.projectSlug,j.id)).executions.map(e=>({jobId:j.id,...e}))))).flat();const [repositories,channel]=await Promise.all([Promise.all(project.repositories.map(github)),discord()]);return NextResponse.json({project,jobs,executions,documents:await listProjectDocuments(project.slug),repositories,integrations:{discord:channel,obsidian:{mode:"filesystem-first",vaultDetected:false,canonicalPath:`projects/${project.slug}`,compatible:true}}});});
