"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import { AlertCircle, Archive, CheckCircle2, FolderKanban, Loader2, Play, Plus, RefreshCw, Users } from "lucide-react";
import { SectionBody, SectionHeader, SectionLayout } from "@/components/section-layout";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { cn } from "@/lib/utils";
import type { JobManifest, JobStatus, ProjectManifest } from "@/lib/clawops-types";

const columns: Array<{ status: JobStatus; label: string }> = [
  { status: "new", label: "New" }, { status: "backlog", label: "Backlog" },
  { status: "in_progress", label: "In Progress" }, { status: "testing", label: "Testing" }, { status: "done", label: "Done" },
];
type Agent = { id: string; name?: string; status?: string; sessionCount?: number };
async function request<T>(url: string, init?: RequestInit): Promise<T> { const r=await fetch(url,{cache:"no-store",...init,headers:{"content-type":"application/json",...init?.headers}}); const b=await r.json().catch(()=>({})); if(!r.ok||b?.ok===false) throw new Error(b?.error||`Request failed (${r.status})`); return b as T; }

export function ClawOpsView() {
 const [projects,setProjects]=useState<ProjectManifest[]>([]),[jobs,setJobs]=useState<JobManifest[]>([]),[agents,setAgents]=useState<Agent[]>([]);
 const [selected,setSelected]=useState(""),[tab,setTab]=useState<"jobs"|"projects"|"team">("jobs"),[loading,setLoading]=useState(true),[error,setError]=useState<string|null>(null),[busy,setBusy]=useState(false);
 const load=useCallback(async()=>{try{const [p,j,a]=await Promise.all([request<{projects:ProjectManifest[]}>("/api/projects"),request<{jobs:JobManifest[]}>("/api/jobs"),request<{agents:Agent[]}>("/api/agents")]);setProjects(p.projects);setJobs(j.jobs);setAgents(a.agents);setSelected(s=>s||p.projects.find(x=>x.status==="active")?.slug||p.projects[0]?.slug||"");setError(null);}catch(e){setError(e instanceof Error?e.message:String(e));}finally{setLoading(false);}},[]);
 useEffect(()=>{void load();},[load]);
 const visible=useMemo(()=>jobs.filter(j=>!selected||j.projectSlug===selected),[jobs,selected]);
 const active=projects.find(p=>p.slug===selected);
 async function mutate(run:()=>Promise<unknown>){setBusy(true);try{await run();await load();}catch(e){setError(e instanceof Error?e.message:String(e));}finally{setBusy(false);}}
 return <SectionLayout><SectionHeader title="ClawOps Mission Control" description="Projects → Jobs → Agents → Executions → Results, backed by the OpenClaw workspace." meta={`${projects.length} projects · ${jobs.length} jobs · ${agents.length} configured agents`} actions={<Button variant="ghost" size="icon-sm" onClick={()=>void load()}><RefreshCw className="size-4"/></Button>}/>
 <SectionBody width="full"><div className="mb-5 flex flex-wrap items-center gap-2"><div className="flex rounded-control bg-secondary p-0.5">{(["jobs","projects","team"] as const).map(t=><button key={t} onClick={()=>setTab(t)} className={cn("rounded-control px-3 py-1.5 text-sm capitalize",tab===t&&"bg-card shadow-sm")}>{t}</button>)}</div>{projects.length>0&&<select className="h-9 rounded-control border border-border bg-card px-3 text-sm" value={selected} onChange={e=>setSelected(e.target.value)}>{projects.map(p=><option key={p.slug} value={p.slug}>{p.name}{p.status==="archived"?" (archived)":""}</option>)}</select>}</div>
 {error&&<div className="mb-4 flex items-center gap-2 rounded-lg border border-danger-border bg-danger-bg p-3 text-sm text-danger-fg"><AlertCircle className="size-4"/>{error}</div>}
 {loading?<div className="flex justify-center py-20"><Loader2 className="size-6 animate-spin"/></div>:tab==="jobs"?<JobsBoard project={active} jobs={visible} agents={agents} busy={busy} mutate={mutate}/>:tab==="projects"?<ProjectsPanel projects={projects} agents={agents} busy={busy} select={setSelected} mutate={mutate}/>:<TeamPanel agents={agents} jobs={visible}/>}</SectionBody></SectionLayout>;
}

function JobsBoard({project,jobs,agents,busy,mutate}:{project?:ProjectManifest;jobs:JobManifest[];agents:Agent[];busy:boolean;mutate:(r:()=>Promise<unknown>)=>Promise<void>}) {
 const [show,setShow]=useState(false),[title,setTitle]=useState(""),[requirements,setRequirements]=useState("");
 const assignee=agents[0]?.id||project?.projectLeadAgentId||"main";
 if(!project)return <Empty icon={FolderKanban} title="Create a Project first" text="Jobs live inside canonical Project directories."/>;
 return <><div className="mb-4 flex items-center justify-between"><div><h2 className="font-semibold">{project.name}</h2><p className="text-xs text-muted-foreground">{project.slug} · Lead: {project.projectLeadAgentId}</p></div><Button size="sm" onClick={()=>setShow(!show)}><Plus/>New Job</Button></div>
 {show&&<Card className="mb-5"><CardContent className="grid gap-3 md:grid-cols-2"><Input value={title} onChange={e=>setTitle(e.target.value)} placeholder="Job title"/><Input value={requirements} onChange={e=>setRequirements(e.target.value)} placeholder="Requirements summary"/><Button disabled={busy||!title.trim()} onClick={()=>void mutate(async()=>{await request(`/api/projects/${project.slug}/jobs`,{method:"POST",body:JSON.stringify({title,type:"implementation",assigneeId:assignee,requirements,requiresTesting:true,actorId:"owner"})});setTitle("");setRequirements("");setShow(false);})}>Create canonical Job</Button></CardContent></Card>}
 <div className="grid min-w-[1050px] grid-cols-5 gap-3 overflow-x-auto pb-3">{columns.map(c=><div key={c.status} className="rounded-xl bg-secondary/45 p-2"><div className="mb-2 flex items-center justify-between px-1"><span className="text-xs font-semibold uppercase tracking-wide">{c.label}</span><Badge variant="secondary">{jobs.filter(j=>j.status===c.status).length}</Badge></div><div className="space-y-2">{jobs.filter(j=>j.status===c.status).map(j=><JobCard key={j.id} job={j} busy={busy} mutate={mutate}/>)}</div></div>)}</div></>;
}
function JobCard({job,busy,mutate}:{job:JobManifest;busy:boolean;mutate:(r:()=>Promise<unknown>)=>Promise<void>}) {const next:Partial<Record<JobStatus,JobStatus>>={new:"backlog",in_progress:job.requiresTesting?"testing":"done",testing:"done"};return <Card className="gap-3 py-4"><CardHeader className="px-4"><div className="flex justify-between gap-2"><CardTitle className="text-sm leading-snug">{job.title}</CardTitle><span className="text-[10px] text-fg-subtle">{job.id}</span></div></CardHeader><CardContent className="space-y-3 px-4"><div className="flex flex-wrap gap-1"><Badge variant="outline">{job.assigneeId}</Badge>{job.indicators.needsOwnerInput&&<Badge variant="warning">Needs input</Badge>}{job.parentJobId&&<Badge variant="secondary">↳ {job.parentJobId}</Badge>}</div><p className="text-xs text-muted-foreground">{job.childJobIds.length} child jobs · priority {job.priority}</p>{next[job.status]&&job.status!=="backlog"&&<Button variant="outline" size="xs" disabled={busy} onClick={()=>void mutate(()=>request(`/api/projects/${job.projectSlug}/jobs/${job.id}`,{method:"PATCH",body:JSON.stringify({status:next[job.status],actorId:"owner",...(next[job.status]==="done"?{result:"Approved from Mission Control"}:{})})}))}>{next[job.status]==="done"?<CheckCircle2/>:<Play/>}{columns.find(c=>c.status===next[job.status])?.label}</Button>}{job.status==="backlog"&&<p className="text-[11px] text-muted-foreground">Starts only after execution evidence is linked.</p>}</CardContent></Card>}
function ProjectsPanel({projects,agents,busy,select,mutate}:{projects:ProjectManifest[];agents:Agent[];busy:boolean;select:(s:string)=>void;mutate:(r:()=>Promise<unknown>)=>Promise<void>}){const [name,setName]=useState(""),[slug,setSlug]=useState("");const lead=agents[0]?.id||"main";return <div className="space-y-4"><Card><CardHeader><CardTitle>New Project</CardTitle></CardHeader><CardContent className="flex flex-wrap gap-2"><Input className="max-w-xs" placeholder="Project name" value={name} onChange={e=>{setName(e.target.value);setSlug(e.target.value.toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,""));}}/><Input className="max-w-xs" placeholder="project-slug" value={slug} onChange={e=>setSlug(e.target.value)}/><Button disabled={busy||!name||!slug} onClick={()=>void mutate(async()=>{await request("/api/projects",{method:"POST",body:JSON.stringify({name,slug,projectLeadAgentId:lead,mission:"Created in ClawOps Mission Control",repositories:[]})});select(slug);setName("");setSlug("");})}><Plus/>Create</Button></CardContent></Card><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{projects.map(p=><Card key={p.slug} className="gap-3"><CardHeader><CardTitle>{p.name}</CardTitle></CardHeader><CardContent><p className="mb-3 text-sm text-muted-foreground">{p.slug} · Lead {p.projectLeadAgentId}</p><Button variant="outline" size="sm" disabled={busy} onClick={()=>void mutate(()=>request(`/api/projects/${p.slug}`,{method:"PATCH",body:JSON.stringify({archived:p.status!=="archived",actorId:"owner"})}))}><Archive/>{p.status==="archived"?"Restore":"Archive"}</Button></CardContent></Card>)}</div></div>}
function TeamPanel({agents,jobs}:{agents:Agent[];jobs:JobManifest[]}){return agents.length===0?<Empty icon={Users} title="No configured agents" text="ClawOps never invents a fake crew."/>:<div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{agents.map(a=><Card key={a.id} className="gap-3"><CardHeader><CardTitle>{a.name||a.id}</CardTitle></CardHeader><CardContent><p className="text-sm text-muted-foreground">{a.id} · {a.status||"unknown"}</p><p className="mt-2 text-sm">{jobs.filter(j=>j.assigneeId===a.id&&j.status!=="done").length} open Jobs · {a.sessionCount||0} sessions</p></CardContent></Card>)}</div>}
function Empty({icon:Icon,title,text}:{icon:typeof Users;title:string;text:string}){return <div className="mx-auto mt-12 max-w-md rounded-xl border border-dashed p-10 text-center"><Icon className="mx-auto mb-3 size-8 text-muted-foreground"/><h2 className="font-semibold">{title}</h2><p className="mt-1 text-sm text-muted-foreground">{text}</p></div>}
